working_dir: /mnt
dataset_dir: /mnt/dataset
num_proc: 16
num_zstd_chunk_size: 1000
temp_file_path: ./temp_refined_warc_samples.jsonl
warc_paths_url: https://data.commoncrawl.org/crawl-data/CC-MAIN-2024-18/warc.paths.gz
fast_text_language_recognition: True
enable_text_extraction_from_html: False
trafilatura_timeout: 30
download_max_trial: -1
process_warc_max_trial: -1