version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - COMPOSE_HTTP_TIMEOUT=86400
    tty: true
    volumes:
      - .:/mnt
    stop_grace_period: 30s
